---

version: "v-{build}"

image: Visual Studio 2017

clone_folder: C:\projects\babashka

environment:
  GRAALVM_HOME: C:\projects\babashka\graalvm\graalvm-ce-java11-22.1.0
  JAVA_HOME: C:\projects\babashka\graalvm\graalvm-ce-java11-22.1.0
  BABASHKA_XMX: "-J-Xmx5g"

skip_commits:
    files:
      - logo/*
      - **/*.md

cache:
  - C:\ProgramData\chocolatey\lib -> project.clj, appveyor.yml
  - '%USERPROFILE%\.m2 -> project.clj'
  - 'graalvm -> appveyor.yml'

clone_script:
- cmd: git config --global core.autocrlf true
- ps: >-
    if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      git clone -q --branch=$env:APPVEYOR_REPO_BRANCH https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git checkout -qf $env:APPVEYOR_REPO_COMMIT
    } else {
      git clone -q https://github.com/$env:APPVEYOR_REPO_NAME.git $env:APPVEYOR_BUILD_FOLDER
      cd $env:APPVEYOR_BUILD_FOLDER
      git fetch -q origin +refs/pull/$env:APPVEYOR_PULL_REQUEST_NUMBER/merge:
      git checkout -qf FETCH_HEAD
    }
- cmd: git submodule update --init --recursive

build_script:
- cmd: >-
    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.1.0/graalvm-ce-java11-windows-amd64-22.1.0.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }"

- cmd: >-
    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')"

    call lein self-install

#- cmd: >-
#    set BABASHKA_TEST_ENV=jvm

#    call script/test.bat

# see https://github.com/quarkusio/quarkus/pull/7663

- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    call script/uberjar.bat

    call script/compile.bat

    echo Creating zip archive

    set zip=babashka-%BABASHKA_VERSION%-windows-amd64.zip

    jar -cMf %zip% bb.exe

    bb --config .build/bb.edn --deps-root . release-artifact %zip%

    set BABASHKA_CLASSPATH=

    set BABASHKA_TEST_ENV=native

    call script/test.bat

    call script/run_lib_tests.bat

artifacts:
- path: babashka-*-windows-amd64.zip
  name: babashka
